### ISSUE TITLE
Overhaul all error messages to use ErrorMessage class

### ISSUE THREAD

**Issue by Kiyoshika** [Kiyoshika/Vertisec#12]
A prettified error message printer has been created, although currently only being used in a couple places within SelectClause. Need to overhaul all error messages to use this prettified version instead.

**Comment by zweaver-chwy** [comment]
in progress as of ad814b6c879eaf88572423e12fa6f3893452ab4d

**Comment by Kiyoshika** [comment]
implemented in eb66aa637cd16f600c1de6f7f035d923039c7e65
